language: node_js
node_js:
- '4'
before_install:
- npm install coveralls
- npm install istanbul
install: npm install
script: npm run-script coveralls
notifications:
  slack:
    secure: fQA8naPmofjIW/xwUiyhXasl7fjSsXesAXUSozc6uJc391/AHSszzsJXKvktzka/8KSjSVzneh1laaES2pF9FpP1zjF8Z/IL4o+M4pMNYYaBS7VnklP6dapTPqUU1L5q5C+U7+F0lDNo8IkElRySygLXJFUu4+iecUrxxMtCkn/lgOllya3HiOOuPU4mNVicVEHYVWj9jWlHxdI+ZLpssdqRUpAO2WKiIJzVegibIE+irK0sqw8vfS0wKyPpi3x0nckMWVliKCseVyB2Zors+6AbFr6/OavMFl8imhAAzoSUCbK5uA3EO3NkGAx/YWV+DFOvm9iw7hmJpMlhpCqV5xQyqWZENJoN7JD++3E3YIuGFJAnt5NCrStKMIsssbWadQSOpblXB//JoOmPe5lTCv4i6EnIkp3LS3Z0oMz9LhFkAoMy1UMcxsrAagl8puu4uDWtTr9QhKCveLBXd0VTgTdYSzZ/ZvdbrwtQ6jlgi75BEKjOijPomtZ8uFTUDkiY50yh45XkDYZbjQ4QtSwwH19taiVMyijgZIJipX6kJlrwb0StkaqSHAWmAXGv6OO7kIByG+MP47MYa7rxsl8uyl3B0k04vAc/EfeKwLkVnr/38hWinBofsJXvoHPIEGHsAf+l2xPk6P8SsjB8HZs24eYFH/2nhhOqeM155Bkt01g=
